require 'minitest/autorun'
require 'pokemongodb'

class LocationTest < Minitest::Test
  describe '.all' do
    it { assert_equal Pokemongodb::Location.all.length, 50 }
  end

  def test_that_to_s_returns_formatted_name
    assert_equal Pokemongodb::Location::Neighborhood.to_s, "neighborhood"
    assert_equal Pokemongodb::Location::NatureReserve.to_s, "nature reserve"
  end

  def test_that_available_pokemon_returns_appropriate_array
    assert_equal Pokemongodb::Location::Beach.available_pokemon, [Pokemongodb::Pokemon::Arcanine, Pokemongodb::Pokemon::Charizard, Pokemongodb::Pokemon::Charmander, Pokemongodb::Pokemon::Charmeleon, Pokemongodb::Pokemon::Flareon, Pokemongodb::Pokemon::Growlithe, Pokemongodb::Pokemon::Magmar, Pokemongodb::Pokemon::Moltres, Pokemongodb::Pokemon::Ninetales, Pokemongodb::Pokemon::Ponyta, Pokemongodb::Pokemon::Rapidash, Pokemongodb::Pokemon::Vulpix, Pokemongodb::Pokemon::Blastoise, Pokemongodb::Pokemon::Cloyster, Pokemongodb::Pokemon::Dewgong, Pokemongodb::Pokemon::Goldeen, Pokemongodb::Pokemon::Golduck, Pokemongodb::Pokemon::Gyarados, Pokemongodb::Pokemon::Horsea, Pokemongodb::Pokemon::Kabuto, Pokemongodb::Pokemon::Kabutops, Pokemongodb::Pokemon::Kingler, Pokemongodb::Pokemon::Krabby, Pokemongodb::Pokemon::Lapras, Pokemongodb::Pokemon::Magikarp, Pokemongodb::Pokemon::Omanyte, Pokemongodb::Pokemon::Omastar, Pokemongodb::Pokemon::Poliwag, Pokemongodb::Pokemon::Poliwhirl, Pokemongodb::Pokemon::Poliwrath, Pokemongodb::Pokemon::Psyduck, Pokemongodb::Pokemon::Seadra, Pokemongodb::Pokemon::Seaking, Pokemongodb::Pokemon::Seel, Pokemongodb::Pokemon::Shellder, Pokemongodb::Pokemon::Slowbro, Pokemongodb::Pokemon::Slowpoke, Pokemongodb::Pokemon::Squirtle, Pokemongodb::Pokemon::Starmie, Pokemongodb::Pokemon::Staryu, Pokemongodb::Pokemon::Tentacool, Pokemongodb::Pokemon::Tentacruel, Pokemongodb::Pokemon::Vaporeon, Pokemongodb::Pokemon::Wartortle]
    assert_equal Pokemongodb::Location::Park.available_pokemon, [Pokemongodb::Pokemon::Beedrill, Pokemongodb::Pokemon::Butterfree, Pokemongodb::Pokemon::Caterpie, Pokemongodb::Pokemon::Kakuna, Pokemongodb::Pokemon::Metapod, Pokemongodb::Pokemon::Paras, Pokemongodb::Pokemon::Parasect, Pokemongodb::Pokemon::Pinsir, Pokemongodb::Pokemon::Scyther, Pokemongodb::Pokemon::Venomoth, Pokemongodb::Pokemon::Venonat, Pokemongodb::Pokemon::Weedle, Pokemongodb::Pokemon::Arcanine, Pokemongodb::Pokemon::Charizard, Pokemongodb::Pokemon::Charmander, Pokemongodb::Pokemon::Charmeleon, Pokemongodb::Pokemon::Flareon, Pokemongodb::Pokemon::Growlithe, Pokemongodb::Pokemon::Magmar, Pokemongodb::Pokemon::Moltres, Pokemongodb::Pokemon::Ninetales, Pokemongodb::Pokemon::Ponyta, Pokemongodb::Pokemon::Rapidash, Pokemongodb::Pokemon::Vulpix, Pokemongodb::Pokemon::Bellsprout, Pokemongodb::Pokemon::Bulbasaur, Pokemongodb::Pokemon::Exeggcute, Pokemongodb::Pokemon::Exeggutor, Pokemongodb::Pokemon::Gloom, Pokemongodb::Pokemon::Ivysaur, Pokemongodb::Pokemon::Oddish, Pokemongodb::Pokemon::Tangela, Pokemongodb::Pokemon::Venusaur, Pokemongodb::Pokemon::Victreebel, Pokemongodb::Pokemon::Vileplume, Pokemongodb::Pokemon::Weepinbell, Pokemongodb::Pokemon::Cubone, Pokemongodb::Pokemon::Diglett, Pokemongodb::Pokemon::Dugtrio, Pokemongodb::Pokemon::Geodude, Pokemongodb::Pokemon::Golem, Pokemongodb::Pokemon::Graveler, Pokemongodb::Pokemon::Marowak, Pokemongodb::Pokemon::Nidoking, Pokemongodb::Pokemon::Nidoqueen, Pokemongodb::Pokemon::Onix, Pokemongodb::Pokemon::Rhydon, Pokemongodb::Pokemon::Rhyhorn, Pokemongodb::Pokemon::Sandshrew, Pokemongodb::Pokemon::Sandslash]
  end
end